---
version: "3.8"

services:
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - 3030:80
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - reports:/reports

  fuzz-ci:
    working_dir: /
    build: ./
    security_opt:
      - seccomp:unconfined
    volumes:
      - reports:/reports
      - corpus:/corpus
      - ./styles:/styles
      - ./checkout.sh:/checkout.sh
      - ./docker/fuzz-ci-config.toml:/fuzz-ci.toml

volumes:
  reports:
  corpus:
